<a href="https://colab.research.google.com/github/ranjuadhikari14/Loss_Function/blob/main/Lossfunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true= np.array([0.30,0.7,1,0,0.5])

In [ ]:
def mean_abs_error(y_true,y_predicted):
  total_error=0
  for ytrue,ypredicted in zip(y_true,y_predicted):
    total_error += abs(ytrue-ypredicted)
  print('total error :', total_error)
  mean_abs_error = total_error / len(y_true)
  print('Mean absolute erroe  :',mean_abs_error)
  return mean_abs_error



In [ ]:
mean_abs_error(y_true,y_predicted)

total error : 2.5
Mean absolute erroe  : 0.5


np.float64(0.5)

In [ ]:
diff=y_predicted - y_true
diff

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [ ]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [ ]:
total_error = np.sum(np.abs(y_predicted-y_true))
total_error

np.float64(2.5)

In [ ]:
#binary cross entropy or log loss

In [ ]:
np.log([0.000001])

array([-13.81551056])

In [ ]:
epsilon = 1e-15


In [ ]:
y_predicted

array([1, 1, 0, 0, 1])

In [ ]:
y_predicted_new =[max(i,eplison)for i in y_predicted]
y_predicted_new

[10.15, 10.15, 10.15, 10.15, 10.15]

In [ ]:
y_predicted_new= [min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[-9.15, -9.15, -9.15, -9.15, -9.15]

In [ ]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

/tmp/ipython-input-32-2029199556.py:2: RuntimeWarning: invalid value encountered in log
  np.log(y_predicted_new)


array([nan, nan, nan, nan, nan])